# =================================================================
# WeWork Platform - 基础共享配置 (开发环境)
# Data ID: basic-config-dev.yml
# Group: wework-platform
# 只包含真正通用的基础配置，不包含业务相关配置
# =================================================================

# JWT配置
jwt:
  secret: ${JWT_SECRET:wework-platform-secret-key-for-jwt-token-generation}
  expiration: 86400000  # 24小时
  refresh-expiration: 604800000  # 7天

# 加密配置
encryption:
  password:
    salt: ${PASSWORD_SALT:wework-platform-password-salt}
    iterations: 10000

# 监控配置
monitoring:
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
  health:
    check-interval: 30000
    failure-threshold: 3

# 日志配置
logging:
  level:
    root: info
    com.wework.platform: debug
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}] [%thread] %-5level [%logger{36}] - %msg%n"
    file: "[%d{yyyy-MM-dd HH:mm:ss}] [%thread] %-5level [%logger{36}] - %msg%n"
  file:
    name: ./logs/wework-platform.log
    max-size: 100MB
    max-history: 30