/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseChart: typeof import('./src/components/charts/BaseChart.vue')['default']
    Copyright: typeof import('./src/components/global/Copyright.vue')['default']
    GlobalConfirm: typeof import('./src/components/global/GlobalConfirm.vue')['default']
    GlobalMessage: typeof import('./src/components/global/GlobalMessage.vue')['default']
    NetworkStatus: typeof import('./src/components/global/NetworkStatus.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Watermark: typeof import('./src/components/global/Watermark.vue')['default']
  }
}
