server:
  port: 18083

spring:
  application:
    name: message-service
  profiles:
    active: docker
    
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:nacos:8848}
        namespace: ${NACOS_NAMESPACE:wework-platform}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        group: DEFAULT_GROUP
        cluster-name: default
        metadata:
          version: 2.0.0
          zone: docker
      config:
        server-addr: ${NACOS_SERVER_ADDR:nacos:8848}
        namespace: ${NACOS_NAMESPACE:wework-platform}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        file-extension: yml
        group: DEFAULT_GROUP

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:mysql}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:wework_platform}?useUnicode=true&characterEncoding=utf8mb4&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:wework}
    password: ${MYSQL_PASSWORD:wework123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
    timeout: 10000
    lettuce:
      pool:
        max-active: 200
        max-idle: 20
        min-idle: 5
        max-wait: -1ms

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    auto-mapping-behavior: partial
  global-config:
    db-config:
      id-type: assign_uuid
      logic-delete-field: deleted_at
      logic-delete-value: now()
      logic-not-delete-value: null
  mapper-locations: classpath*:/mapper/**/*.xml

rocketmq:
  name-server: ${ROCKETMQ_NAMESERVER:rocketmq-nameserver:9876}
  producer:
    group: message-service-producer-group
    send-message-timeout: 30000
    retry-times-when-send-failed: 2
  consumer:
    group: message-service-consumer-group

# WeWork API配置
wework:
  api:
    base-url: https://qyapi.weixin.qq.com
    timeout: 30000
    retry-count: 3
  message:
    max-batch-size: 1000
    rate-limit:
      enabled: true
      requests-per-minute: 10000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    com.wework.platform: DEBUG
    com.baomidou.mybatisplus: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"