server:
  port: ${PORT:8083}
  servlet:
    context-path: /monitor

spring:
  profiles:
    active: ${PROFILE:dev}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:wework_platform}?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:123456}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: MonitorHikariPool

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: ${REDIS_DATABASE:2}
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 2
        max-wait: 3000ms

  cloud:
    sentinel:
      transport:
        dashboard: ${SENTINEL_DASHBOARD:localhost:8858}
        port: ${SENTINEL_PORT:8719}

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.wework.platform.monitor.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    auto-mapping-behavior: partial
  global-config:
    db-config:
      id-type: assign_uuid
      logic-delete-field: deleted_at
      logic-delete-value: now()
      logic-not-delete-value: null

logging:
  level:
    com.wework.platform.monitor: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{50}] - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# 应用配置
app:
  monitor:
    metric:
      retention-days: 30
      batch-size: 100
      max-query-limit: 1000
      enable-compression: true
    alert:
      retention-days: 90
      evaluation-interval: 60
      max-alert-count: 10000
      enable-auto-evaluation: true
      notification-retry-count: 3
      notification-timeout: 30
    cleanup:
      cron-expression: "0 0 2 * * ?"
      enable-auto-cleanup: true
      batch-size: 1000
    notification:
      enable-email: true
      enable-sms: false
      enable-webhook: true
      enable-wework: true